# Generated by Django 4.1.13 on 2024-08-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorupload',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='question',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='ProfessorUpload',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
